(function(){
/*

 Copyright (c) 2016 The Polymer Project Authors. All rights reserved.
 This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
 The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
 The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
 Code distributed by Google as part of the polymer project is also
 subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt

Copyright (c) 2017 The Polymer Project Authors. All rights reserved.
This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
Code distributed by Google as part of the polymer project is also
subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt
*/
'use strict';(function(){function Q(b){function a(d,a){Object.defineProperty(d,"innerHTML",{enumerable:a.enumerable,configurable:!0,get:a.get,set:function(d){var e=this,f=void 0;g(this)&&(f=[],q(this,function(b){b!==e&&f.push(b)}));a.set.call(this,d);if(f)for(var c=0;c<f.length;c++){var k=f[c];1===k.__CE_state&&b.disconnectedCallback(k)}this.ownerDocument.__CE_hasRegistry?b.patchAndUpgradeTree(this):b.patchTree(this);return d}})}function f(a,e){l(a,"insertAdjacentElement",function(a,d){var f=g(d);
a=e.call(this,a,d);f&&b.disconnectTree(d);g(a)&&b.connectTree(d);return a})}D?l(Element.prototype,"attachShadow",function(b){return this.__CE_shadowRoot=b=D.call(this,b)}):console.warn("Custom Elements: `Element#attachShadow` was not patched.");if(u&&u.get)a(Element.prototype,u);else if(v&&v.get)a(HTMLElement.prototype,v);else{var c=w.call(document,"div");b.addPatch(function(b){a(b,{enumerable:!0,configurable:!0,get:function(){return E.call(this,!0).innerHTML},set:function(b){var a="template"===this.localName?
this.content:this;for(c.innerHTML=b;0<a.childNodes.length;)x.call(a,a.childNodes[0]);for(;0<c.childNodes.length;)r.call(a,c.childNodes[0])}})})}l(Element.prototype,"setAttribute",function(a,e){if(1!==this.__CE_state)return F.call(this,a,e);var d=y.call(this,a);F.call(this,a,e);e=y.call(this,a);d!==e&&b.attributeChangedCallback(this,a,d,e,null)});l(Element.prototype,"setAttributeNS",function(a,e,f){if(1!==this.__CE_state)return G.call(this,a,e,f);var d=t.call(this,a,e);G.call(this,a,e,f);f=t.call(this,
a,e);d!==f&&b.attributeChangedCallback(this,e,d,f,a)});l(Element.prototype,"removeAttribute",function(a){if(1!==this.__CE_state)return H.call(this,a);var d=y.call(this,a);H.call(this,a);null!==d&&b.attributeChangedCallback(this,a,d,null,null)});l(Element.prototype,"removeAttributeNS",function(a,f){if(1!==this.__CE_state)return I.call(this,a,f);var d=t.call(this,a,f);I.call(this,a,f);var e=t.call(this,a,f);d!==e&&b.attributeChangedCallback(this,f,d,e,a)});J?f(HTMLElement.prototype,J):K?f(Element.prototype,
K):console.warn("Custom Elements: `Element#insertAdjacentElement` was not patched.");L(b,Element.prototype,{prepend:R,append:S});T(b,Element.prototype,{before:U,after:V,replaceWith:W,remove:X})}function T(b,a,f){a.before=function(a){for(var d=[],e=0;e<arguments.length;++e)d[e-0]=arguments[e];e=d.filter(function(b){return b instanceof Node&&g(b)});f.before.apply(this,d);for(var c=0;c<e.length;c++)b.disconnectTree(e[c]);if(g(this))for(e=0;e<d.length;e++)c=d[e],c instanceof Element&&b.connectTree(c)};
a.after=function(a){for(var d=[],e=0;e<arguments.length;++e)d[e-0]=arguments[e];e=d.filter(function(b){return b instanceof Node&&g(b)});f.after.apply(this,d);for(var c=0;c<e.length;c++)b.disconnectTree(e[c]);if(g(this))for(e=0;e<d.length;e++)c=d[e],c instanceof Element&&b.connectTree(c)};a.replaceWith=function(a){for(var d=[],c=0;c<arguments.length;++c)d[c-0]=arguments[c];var c=d.filter(function(b){return b instanceof Node&&g(b)}),k=g(this);f.replaceWith.apply(this,d);for(var p=0;p<c.length;p++)b.disconnectTree(c[p]);
if(k)for(b.disconnectTree(this),c=0;c<d.length;c++)k=d[c],k instanceof Element&&b.connectTree(k)};a.remove=function(){var a=g(this);f.remove.call(this);a&&b.disconnectTree(this)}}function Y(b){function a(a,c){Object.defineProperty(a,"textContent",{enumerable:c.enumerable,configurable:!0,get:c.get,set:function(a){if(this.nodeType===Node.TEXT_NODE)c.set.call(this,a);else{var f=void 0;if(this.firstChild){var d=this.childNodes,p=d.length;if(0<p&&g(this))for(var f=Array(p),h=0;h<p;h++)f[h]=d[h]}c.set.call(this,
a);if(f)for(a=0;a<f.length;a++)b.disconnectTree(f[a])}}})}l(Node.prototype,"insertBefore",function(a,c){if(a instanceof DocumentFragment){var d=Array.prototype.slice.apply(a.childNodes);a=M.call(this,a,c);if(g(this))for(c=0;c<d.length;c++)b.connectTree(d[c]);return a}d=g(a);c=M.call(this,a,c);d&&b.disconnectTree(a);g(this)&&b.connectTree(a);return c});l(Node.prototype,"appendChild",function(a){if(a instanceof DocumentFragment){var c=Array.prototype.slice.apply(a.childNodes);a=r.call(this,a);if(g(this))for(var d=
0;d<c.length;d++)b.connectTree(c[d]);return a}c=g(a);d=r.call(this,a);c&&b.disconnectTree(a);g(this)&&b.connectTree(a);return d});l(Node.prototype,"cloneNode",function(a){a=E.call(this,a);this.ownerDocument.__CE_hasRegistry?b.patchAndUpgradeTree(a):b.patchTree(a);return a});l(Node.prototype,"removeChild",function(a){var c=g(a),d=x.call(this,a);c&&b.disconnectTree(a);return d});l(Node.prototype,"replaceChild",function(a,c){if(a instanceof DocumentFragment){var d=Array.prototype.slice.apply(a.childNodes);
a=N.call(this,a,c);if(g(this))for(b.disconnectTree(c),c=0;c<d.length;c++)b.connectTree(d[c]);return a}var d=g(a),e=N.call(this,a,c),f=g(this);f&&b.disconnectTree(c);d&&b.disconnectTree(a);f&&b.connectTree(a);return e});z&&z.get?a(Node.prototype,z):b.addPatch(function(b){a(b,{enumerable:!0,configurable:!0,get:function(){for(var a=[],b=0;b<this.childNodes.length;b++)a.push(this.childNodes[b].textContent);return a.join("")},set:function(a){for(;this.firstChild;)x.call(this,this.firstChild);r.call(this,
document.createTextNode(a))}})})}function Z(b){l(Document.prototype,"createElement",function(a){if(this.__CE_hasRegistry){var f=b.localNameToDefinition(a);if(f)return new f.constructor}a=w.call(this,a);b.patch(a);return a});l(Document.prototype,"importNode",function(a,f){a=aa.call(this,a,f);this.__CE_hasRegistry?b.patchAndUpgradeTree(a):b.patchTree(a);return a});l(Document.prototype,"createElementNS",function(a,f){if(this.__CE_hasRegistry&&(null===a||"http://www.w3.org/1999/xhtml"===a)){var c=b.localNameToDefinition(f);
if(c)return new c.constructor}a=ba.call(this,a,f);b.patch(a);return a});L(b,Document.prototype,{prepend:ca,append:da})}function L(b,a,f){a.prepend=function(a){for(var c=[],e=0;e<arguments.length;++e)c[e-0]=arguments[e];e=c.filter(function(a){return a instanceof Node&&g(a)});f.prepend.apply(this,c);for(var k=0;k<e.length;k++)b.disconnectTree(e[k]);if(g(this))for(e=0;e<c.length;e++)k=c[e],k instanceof Element&&b.connectTree(k)};a.append=function(a){for(var c=[],e=0;e<arguments.length;++e)c[e-0]=arguments[e];
e=c.filter(function(a){return a instanceof Node&&g(a)});f.append.apply(this,c);for(var k=0;k<e.length;k++)b.disconnectTree(e[k]);if(g(this))for(e=0;e<c.length;e++)k=c[e],k instanceof Element&&b.connectTree(k)}}function ea(b){window.HTMLElement=function(){function a(){var a=this.constructor,c=b.constructorToDefinition(a);if(!c)throw Error("The custom element being constructed was not registered with `customElements`.");var d=c.constructionStack;if(0===d.length)return d=w.call(document,c.localName),
Object.setPrototypeOf(d,a.prototype),d.__CE_state=1,d.__CE_definition=c,b.patch(d),d;var c=d.length-1,e=d[c];if(e===O)throw Error("The HTMLElement constructor was either called reentrantly for this constructor or called multiple times.");d[c]=O;Object.setPrototypeOf(e,a.prototype);b.patch(e);return e}a.prototype=fa.prototype;return a}()}function h(b){this._elementDefinitionIsRunning=!1;this._internals=b;this._whenDefinedDeferred=new Map;this._flushCallback=function(a){return a()};this._flushPending=
!1;this._unflushedLocalNames=[];this._documentConstructionObserver=new A(b,document)}function B(){var b=this;this._resolve=this._value=void 0;this._promise=new Promise(function(a){b._resolve=a;b._value&&a(b._value)})}function A(b,a){this._internals=b;this._document=a;this._observer=void 0;this._internals.patchAndUpgradeTree(this._document);"loading"===this._document.readyState&&(this._observer=new MutationObserver(this._handleMutations.bind(this)),this._observer.observe(this._document,{childList:!0,
subtree:!0}))}function m(){this._localNameToDefinition=new Map;this._constructorToDefinition=new Map;this._patches=[];this._hasPatches=!1}function P(b){var a=ga.has(b);b=/^[a-z][.0-9_a-z]*-[\-.0-9_a-z]*$/.test(b);return!a&&b}function g(b){var a=b.isConnected;if(void 0!==a)return a;for(;b&&!(b.__CE_isImportDocument||b instanceof Document);)b=b.parentNode||(window.ShadowRoot&&b instanceof ShadowRoot?b.host:void 0);return!(!b||!(b.__CE_isImportDocument||b instanceof Document))}function C(b,a){for(;a&&
a!==b&&!a.nextSibling;)a=a.parentNode;return a&&a!==b?a.nextSibling:null}function q(b,a,f){f=void 0===f?new Set:f;for(var c=b;c;){if(c.nodeType===Node.ELEMENT_NODE){var d=c;a(d);var e=d.localName;if("link"===e&&"import"===d.getAttribute("rel")){c=d.import;if(c instanceof Node&&!f.has(c))for(f.add(c),c=c.firstChild;c;c=c.nextSibling)q(c,a,f);c=C(b,d);continue}else if("template"===e){c=C(b,d);continue}if(d=d.__CE_shadowRoot)for(d=d.firstChild;d;d=d.nextSibling)q(d,a,f)}c=c.firstChild?c.firstChild:C(b,
c)}}function l(b,a,f){b[a]=f}var ga=new Set("annotation-xml color-profile font-face font-face-src font-face-uri font-face-format font-face-name missing-glyph".split(" "));m.prototype.setDefinition=function(b,a){this._localNameToDefinition.set(b,a);this._constructorToDefinition.set(a.constructor,a)};m.prototype.localNameToDefinition=function(b){return this._localNameToDefinition.get(b)};m.prototype.constructorToDefinition=function(b){return this._constructorToDefinition.get(b)};m.prototype.addPatch=
function(b){this._hasPatches=!0;this._patches.push(b)};m.prototype.patchTree=function(b){var a=this;this._hasPatches&&q(b,function(b){return a.patch(b)})};m.prototype.patch=function(b){if(this._hasPatches&&!b.__CE_patched){b.__CE_patched=!0;for(var a=0;a<this._patches.length;a++)this._patches[a](b)}};m.prototype.connectTree=function(b){var a=[];q(b,function(b){return a.push(b)});for(b=0;b<a.length;b++){var f=a[b];1===f.__CE_state?this.connectedCallback(f):this.upgradeElement(f)}};m.prototype.disconnectTree=
function(b){var a=[];q(b,function(b){return a.push(b)});for(b=0;b<a.length;b++){var f=a[b];1===f.__CE_state&&this.disconnectedCallback(f)}};m.prototype.patchAndUpgradeTree=function(b,a){a=void 0===a?new Set:a;var f=this,c=[];q(b,function(b){if("link"===b.localName&&"import"===b.getAttribute("rel")){var d=b.import;d instanceof Node&&"complete"===d.readyState?(d.__CE_isImportDocument=!0,d.__CE_hasRegistry=!0):b.addEventListener("load",function(){var c=b.import;c.__CE_documentLoadHandled||(c.__CE_documentLoadHandled=
!0,c.__CE_isImportDocument=!0,c.__CE_hasRegistry=!0,new Set(a),a.delete(c),f.patchAndUpgradeTree(c,a))})}else c.push(b)},a);if(this._hasPatches)for(b=0;b<c.length;b++)this.patch(c[b]);for(b=0;b<c.length;b++)this.upgradeElement(c[b])};m.prototype.upgradeElement=function(b){if(void 0===b.__CE_state){var a=this.localNameToDefinition(b.localName);if(a){a.constructionStack.push(b);var f=a.constructor;try{try{if(new f!==b)throw Error("The custom element constructor did not produce the element being upgraded.");
}finally{a.constructionStack.pop()}}catch(e){throw b.__CE_state=2,e;}b.__CE_state=1;b.__CE_definition=a;if(a.attributeChangedCallback)for(a=a.observedAttributes,f=0;f<a.length;f++){var c=a[f],d=b.getAttribute(c);null!==d&&this.attributeChangedCallback(b,c,null,d,null)}g(b)&&this.connectedCallback(b)}}};m.prototype.connectedCallback=function(b){var a=b.__CE_definition;a.connectedCallback&&a.connectedCallback.call(b)};m.prototype.disconnectedCallback=function(b){var a=b.__CE_definition;a.disconnectedCallback&&
a.disconnectedCallback.call(b)};m.prototype.attributeChangedCallback=function(b,a,f,c,d){var e=b.__CE_definition;e.attributeChangedCallback&&-1<e.observedAttributes.indexOf(a)&&e.attributeChangedCallback.call(b,a,f,c,d)};A.prototype.disconnect=function(){this._observer&&this._observer.disconnect()};A.prototype._handleMutations=function(b){var a=this._document.readyState;"interactive"!==a&&"complete"!==a||this.disconnect();for(a=0;a<b.length;a++)for(var f=b[a].addedNodes,c=0;c<f.length;c++)this._internals.patchAndUpgradeTree(f[c])};
B.prototype.resolve=function(b){if(this._value)throw Error("Already resolved.");this._value=b;this._resolve&&this._resolve(b)};B.prototype.toPromise=function(){return this._promise};h.prototype.define=function(b,a){var f=this;if(!(a instanceof Function))throw new TypeError("Custom element constructors must be functions.");if(!P(b))throw new SyntaxError("The element name '"+b+"' is not valid.");if(this._internals.localNameToDefinition(b))throw Error("A custom element with name '"+b+"' has already been defined.");
if(this._elementDefinitionIsRunning)throw Error("A custom element is already being defined.");this._elementDefinitionIsRunning=!0;var c,d,e,g,h;try{var l=function(a){var b=m[a];if(void 0!==b&&!(b instanceof Function))throw Error("The '"+a+"' callback must be a function.");return b},m=a.prototype;if(!(m instanceof Object))throw new TypeError("The custom element constructor's prototype is not an object.");c=l("connectedCallback");d=l("disconnectedCallback");e=l("adoptedCallback");g=l("attributeChangedCallback");
h=a.observedAttributes||[]}catch(ha){return}finally{this._elementDefinitionIsRunning=!1}this._internals.setDefinition(b,{localName:b,constructor:a,connectedCallback:c,disconnectedCallback:d,adoptedCallback:e,attributeChangedCallback:g,observedAttributes:h,constructionStack:[]});this._unflushedLocalNames.push(b);this._flushPending||(this._flushPending=!0,this._flushCallback(function(){return f._flush()}))};h.prototype._flush=function(){if(!1!==this._flushPending)for(this._flushPending=!1,this._internals.patchAndUpgradeTree(document);0<
this._unflushedLocalNames.length;){var b=this._unflushedLocalNames.shift();(b=this._whenDefinedDeferred.get(b))&&b.resolve(void 0)}};h.prototype.get=function(b){if(b=this._internals.localNameToDefinition(b))return b.constructor};h.prototype.whenDefined=function(b){if(!P(b))return Promise.reject(new SyntaxError("'"+b+"' is not a valid custom element name."));var a=this._whenDefinedDeferred.get(b);if(a)return a.toPromise();a=new B;this._whenDefinedDeferred.set(b,a);this._internals.localNameToDefinition(b)&&
-1===this._unflushedLocalNames.indexOf(b)&&a.resolve(void 0);return a.toPromise()};h.prototype.polyfillWrapFlushCallback=function(b){this._documentConstructionObserver.disconnect();var a=this._flushCallback;this._flushCallback=function(f){return b(function(){return a(f)})}};window.CustomElementRegistry=h;h.prototype.define=h.prototype.define;h.prototype.get=h.prototype.get;h.prototype.whenDefined=h.prototype.whenDefined;h.prototype.polyfillWrapFlushCallback=h.prototype.polyfillWrapFlushCallback;var w=
window.Document.prototype.createElement,ba=window.Document.prototype.createElementNS,aa=window.Document.prototype.importNode,ca=window.Document.prototype.prepend,da=window.Document.prototype.append,E=window.Node.prototype.cloneNode,r=window.Node.prototype.appendChild,M=window.Node.prototype.insertBefore,x=window.Node.prototype.removeChild,N=window.Node.prototype.replaceChild,z=Object.getOwnPropertyDescriptor(window.Node.prototype,"textContent"),D=window.Element.prototype.attachShadow,u=Object.getOwnPropertyDescriptor(window.Element.prototype,
"innerHTML"),y=window.Element.prototype.getAttribute,F=window.Element.prototype.setAttribute,H=window.Element.prototype.removeAttribute,t=window.Element.prototype.getAttributeNS,G=window.Element.prototype.setAttributeNS,I=window.Element.prototype.removeAttributeNS,K=window.Element.prototype.insertAdjacentElement,R=window.Element.prototype.prepend,S=window.Element.prototype.append,U=window.Element.prototype.before,V=window.Element.prototype.after,W=window.Element.prototype.replaceWith,X=window.Element.prototype.remove,
fa=window.HTMLElement,v=Object.getOwnPropertyDescriptor(window.HTMLElement.prototype,"innerHTML"),J=window.HTMLElement.prototype.insertAdjacentElement,O=new function(){},n=window.customElements;if(!n||n.forcePolyfill||"function"!=typeof n.define||"function"!=typeof n.get)n=new m,ea(n),Z(n),Y(n),Q(n),document.__CE_hasRegistry=!0,n=new h(n),Object.defineProperty(window,"customElements",{configurable:!0,enumerable:!0,value:n})})();
}).call(self)

//# sourceMappingURL=webcomponents-ce.js.map
